// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieManager.Models;

#nullable disable

namespace MovieManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieManager.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Action",
                            ReleaseYear = "2022",
                            Title = "Uncharted"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Action",
                            ReleaseYear = "2021",
                            Title = "Shang-Chi and the Legend of the Ten Rings"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            ReleaseYear = "2022",
                            Title = "Spider-Man: No Way Home"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Action",
                            ReleaseYear = "2023",
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Action",
                            ReleaseYear = "2019",
                            Title = "Captain Marvel"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Action",
                            ReleaseYear = "2019",
                            Title = "Alita: Battle Angel"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Action",
                            ReleaseYear = "2020",
                            Title = "Demon Slayer the Movie: Mugen Train"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Action",
                            ReleaseYear = "2018",
                            Title = "Dragon Ball Super: Broly"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Action",
                            ReleaseYear = "2022",
                            Title = "Dragon Ball Super: Super Hero"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Action",
                            ReleaseYear = "2021",
                            Title = "Jujutsu Kaisen 0"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Action",
                            ReleaseYear = "1988",
                            Title = "Akira"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Adventure",
                            ReleaseYear = "2014",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Adventure",
                            ReleaseYear = "2012",
                            Title = "Life of Pi"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Adventure",
                            ReleaseYear = "2022",
                            Title = "The Batman"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Adventure",
                            ReleaseYear = "2015",
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Adventure",
                            ReleaseYear = "1982",
                            Title = "E.T. the Extra-Terrestrial"
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Adventure",
                            ReleaseYear = "2016",
                            Title = "The Jungle Book"
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Adventure",
                            ReleaseYear = "2006",
                            Title = "Paprika"
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Adventure",
                            ReleaseYear = "2001",
                            Title = "Spirited Away"
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Adventure",
                            ReleaseYear = "2002",
                            Title = "The Cat Returns"
                        },
                        new
                        {
                            Id = 21,
                            Genre = "Adventure",
                            ReleaseYear = "1997",
                            Title = "Princess Mononoke"
                        },
                        new
                        {
                            Id = 22,
                            Genre = "Comedy",
                            ReleaseYear = "2017",
                            Title = "Baywatch"
                        },
                        new
                        {
                            Id = 23,
                            Genre = "Comedy",
                            ReleaseYear = "1998",
                            Title = "Rush Hour"
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Comedy",
                            ReleaseYear = "2001",
                            Title = "Rush Hour 2"
                        },
                        new
                        {
                            Id = 25,
                            Genre = "Comedy",
                            ReleaseYear = "2007",
                            Title = "Rush Hour 3"
                        },
                        new
                        {
                            Id = 26,
                            Genre = "Comedy",
                            ReleaseYear = "1995",
                            Title = "Bad Boys"
                        },
                        new
                        {
                            Id = 27,
                            Genre = "Comedy",
                            ReleaseYear = "2003",
                            Title = "Bad Boys 2"
                        },
                        new
                        {
                            Id = 28,
                            Genre = "Comedy",
                            ReleaseYear = "2013",
                            Title = "Gintama Movie: Kanketsu-hen"
                        },
                        new
                        {
                            Id = 29,
                            Genre = "Comedy",
                            ReleaseYear = "2016",
                            Title = "Konosuba: God's Blessing On This Wonderful World!"
                        },
                        new
                        {
                            Id = 30,
                            Genre = "Comedy",
                            ReleaseYear = "2016",
                            Title = "Haven't You Heard? I'm SAKAMOTO"
                        },
                        new
                        {
                            Id = 31,
                            Genre = "Comedy",
                            ReleaseYear = "2013",
                            Title = "K On! Movie"
                        },
                        new
                        {
                            Id = 32,
                            Genre = "Mystery",
                            ReleaseYear = "2020",
                            Title = "Hit"
                        },
                        new
                        {
                            Id = 33,
                            Genre = "Mystery",
                            ReleaseYear = "2022",
                            Title = "Vikram"
                        },
                        new
                        {
                            Id = 34,
                            Genre = "Mystery",
                            ReleaseYear = "2022",
                            Title = "Freddy"
                        },
                        new
                        {
                            Id = 35,
                            Genre = "Mystery",
                            ReleaseYear = "2011",
                            Title = "Source Code"
                        },
                        new
                        {
                            Id = 36,
                            Genre = "Mystery",
                            ReleaseYear = "2012",
                            Title = "Talaash: The Answer Lies Within"
                        },
                        new
                        {
                            Id = 37,
                            Genre = "Mystery",
                            ReleaseYear = "2000",
                            Title = "American Psycho"
                        },
                        new
                        {
                            Id = 38,
                            Genre = "Mystery",
                            ReleaseYear = "1997",
                            Title = "Perfect Blue"
                        },
                        new
                        {
                            Id = 39,
                            Genre = "Mystery",
                            ReleaseYear = "2016",
                            Title = "Erased"
                        },
                        new
                        {
                            Id = 40,
                            Genre = "Mystery",
                            ReleaseYear = "2020",
                            Title = "When Marnie Was There "
                        },
                        new
                        {
                            Id = 41,
                            Genre = "Mystery",
                            ReleaseYear = "2006",
                            Title = "The Girl Who Leapt Through Time"
                        },
                        new
                        {
                            Id = 42,
                            Genre = "Romantic",
                            ReleaseYear = "2009",
                            Title = "Magadheera"
                        },
                        new
                        {
                            Id = 43,
                            Genre = "Romantic",
                            ReleaseYear = "2022",
                            Title = "Gurthunda Seethakalam"
                        },
                        new
                        {
                            Id = 44,
                            Genre = "Romantic",
                            ReleaseYear = "2008",
                            Title = "Ghajini"
                        },
                        new
                        {
                            Id = 45,
                            Genre = "Romantic",
                            ReleaseYear = "2017",
                            Title = "Arjun Reddy"
                        },
                        new
                        {
                            Id = 46,
                            Genre = "Romantic",
                            ReleaseYear = "2009",
                            Title = "Sita Ramam"
                        },
                        new
                        {
                            Id = 47,
                            Genre = "Romantic",
                            ReleaseYear = "2018",
                            Title = "Geetha Govindam"
                        },
                        new
                        {
                            Id = 48,
                            Genre = "Romantic",
                            ReleaseYear = "2014",
                            Title = "Tamako Love Story"
                        },
                        new
                        {
                            Id = 49,
                            Genre = "Romantic",
                            ReleaseYear = "2018",
                            Title = "I Want to Eat Your Pancreas"
                        },
                        new
                        {
                            Id = 50,
                            Genre = "Romantic",
                            ReleaseYear = "2017",
                            Title = "Your Name"
                        },
                        new
                        {
                            Id = 51,
                            Genre = "Romantic",
                            ReleaseYear = "2007",
                            Title = "5 Centimeters per Second"
                        },
                        new
                        {
                            Id = 52,
                            Genre = "Drama",
                            ReleaseYear = "2018",
                            Title = "Rangasthalam"
                        },
                        new
                        {
                            Id = 53,
                            Genre = "Drama",
                            ReleaseYear = "2019",
                            Title = "Uri: The Surgical Strike"
                        },
                        new
                        {
                            Id = 54,
                            Genre = "Drama",
                            ReleaseYear = "2019",
                            Title = "Kesari"
                        },
                        new
                        {
                            Id = 55,
                            Genre = "Drama",
                            ReleaseYear = "2018",
                            Title = "Parmanu: The Story of Pokhran"
                        },
                        new
                        {
                            Id = 56,
                            Genre = "Drama",
                            ReleaseYear = "2018",
                            Title = "Raazi"
                        },
                        new
                        {
                            Id = 57,
                            Genre = "Drama",
                            ReleaseYear = "2016",
                            Title = "Dangal"
                        },
                        new
                        {
                            Id = 58,
                            Genre = "Drama",
                            ReleaseYear = "2011",
                            Title = "Singham"
                        },
                        new
                        {
                            Id = 59,
                            Genre = "Drama",
                            ReleaseYear = "2018",
                            Title = "Bhavesh Joshi Superhero"
                        },
                        new
                        {
                            Id = 60,
                            Genre = "Drama",
                            ReleaseYear = "2015",
                            Title = "Badlapur"
                        },
                        new
                        {
                            Id = 61,
                            Genre = "Drama",
                            ReleaseYear = "2022",
                            Title = "RRR"
                        },
                        new
                        {
                            Id = 62,
                            Genre = "Horror",
                            ReleaseYear = "2007",
                            Title = "I Am Legend"
                        },
                        new
                        {
                            Id = 63,
                            Genre = "Horror",
                            ReleaseYear = "2022",
                            Title = "Prey"
                        },
                        new
                        {
                            Id = 64,
                            Genre = "Horror",
                            ReleaseYear = "2008",
                            Title = "Cloverfield"
                        },
                        new
                        {
                            Id = 65,
                            Genre = "Horror",
                            ReleaseYear = "2013",
                            Title = "World War Z"
                        },
                        new
                        {
                            Id = 66,
                            Genre = "Horror",
                            ReleaseYear = "1973",
                            Title = "The Exorcist"
                        },
                        new
                        {
                            Id = 67,
                            Genre = "Horror",
                            ReleaseYear = "2014",
                            Title = "As Above, So Below"
                        },
                        new
                        {
                            Id = 68,
                            Genre = "Horror",
                            ReleaseYear = "2021",
                            Title = "Paranormal Activity"
                        },
                        new
                        {
                            Id = 69,
                            Genre = "Horror",
                            ReleaseYear = "1999",
                            Title = "The Blair Witch Project"
                        },
                        new
                        {
                            Id = 70,
                            Genre = "Horror",
                            ReleaseYear = "2010",
                            Title = "Insidious"
                        },
                        new
                        {
                            Id = 71,
                            Genre = "Horror",
                            ReleaseYear = "2004",
                            Title = "The Grudge"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
